package com.zzt.demo.model;

import org.apache.ibatis.type.Alias;

import java.util.Date;
// 可以不写这个注解，配置文件已经扫描了这个包，默认为首字母小写的类名，但实际全小写也能找到
@Alias("tProduct")
public class TProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.product_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.product_spec_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private String productSpecId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.offering_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private String offeringId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.customer_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.contract_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private String contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.offering_spec_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private String offeringSpecId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.effective_start_dt
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private Date effectiveStartDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.effective_end_dt
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private Date effectiveEndDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.column1
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private String column1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.product_status
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private String productStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.customer_tel_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private String customerTelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.times
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private Long times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.duration
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private Long duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.flux
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private Long flux;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.source
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.area_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.crm_order_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private String crmOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.memo
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.product_id
     *
     * @return the value of t_product.product_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.product_id
     *
     * @param productId the value for t_product.product_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.product_spec_id
     *
     * @return the value of t_product.product_spec_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public String getProductSpecId() {
        return productSpecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.product_spec_id
     *
     * @param productSpecId the value for t_product.product_spec_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setProductSpecId(String productSpecId) {
        this.productSpecId = productSpecId == null ? null : productSpecId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.offering_id
     *
     * @return the value of t_product.offering_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public String getOfferingId() {
        return offeringId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.offering_id
     *
     * @param offeringId the value for t_product.offering_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setOfferingId(String offeringId) {
        this.offeringId = offeringId == null ? null : offeringId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.customer_id
     *
     * @return the value of t_product.customer_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.customer_id
     *
     * @param customerId the value for t_product.customer_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.contract_id
     *
     * @return the value of t_product.contract_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.contract_id
     *
     * @param contractId the value for t_product.contract_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setContractId(String contractId) {
        this.contractId = contractId == null ? null : contractId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.offering_spec_id
     *
     * @return the value of t_product.offering_spec_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public String getOfferingSpecId() {
        return offeringSpecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.offering_spec_id
     *
     * @param offeringSpecId the value for t_product.offering_spec_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setOfferingSpecId(String offeringSpecId) {
        this.offeringSpecId = offeringSpecId == null ? null : offeringSpecId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.effective_start_dt
     *
     * @return the value of t_product.effective_start_dt
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public Date getEffectiveStartDt() {
        return effectiveStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.effective_start_dt
     *
     * @param effectiveStartDt the value for t_product.effective_start_dt
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setEffectiveStartDt(Date effectiveStartDt) {
        this.effectiveStartDt = effectiveStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.effective_end_dt
     *
     * @return the value of t_product.effective_end_dt
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public Date getEffectiveEndDt() {
        return effectiveEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.effective_end_dt
     *
     * @param effectiveEndDt the value for t_product.effective_end_dt
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setEffectiveEndDt(Date effectiveEndDt) {
        this.effectiveEndDt = effectiveEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.column1
     *
     * @return the value of t_product.column1
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.column1
     *
     * @param column1 the value for t_product.column1
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setColumn1(String column1) {
        this.column1 = column1 == null ? null : column1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.product_status
     *
     * @return the value of t_product.product_status
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public String getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.product_status
     *
     * @param productStatus the value for t_product.product_status
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus == null ? null : productStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.customer_tel_id
     *
     * @return the value of t_product.customer_tel_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public String getCustomerTelId() {
        return customerTelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.customer_tel_id
     *
     * @param customerTelId the value for t_product.customer_tel_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setCustomerTelId(String customerTelId) {
        this.customerTelId = customerTelId == null ? null : customerTelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.times
     *
     * @return the value of t_product.times
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public Long getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.times
     *
     * @param times the value for t_product.times
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setTimes(Long times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.duration
     *
     * @return the value of t_product.duration
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.duration
     *
     * @param duration the value for t_product.duration
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.flux
     *
     * @return the value of t_product.flux
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public Long getFlux() {
        return flux;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.flux
     *
     * @param flux the value for t_product.flux
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setFlux(Long flux) {
        this.flux = flux;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.source
     *
     * @return the value of t_product.source
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.source
     *
     * @param source the value for t_product.source
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.area_id
     *
     * @return the value of t_product.area_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.area_id
     *
     * @param areaId the value for t_product.area_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.crm_order_id
     *
     * @return the value of t_product.crm_order_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public String getCrmOrderId() {
        return crmOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.crm_order_id
     *
     * @param crmOrderId the value for t_product.crm_order_id
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setCrmOrderId(String crmOrderId) {
        this.crmOrderId = crmOrderId == null ? null : crmOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.memo
     *
     * @return the value of t_product.memo
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.memo
     *
     * @param memo the value for t_product.memo
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}