package com.zzt.demo.model;

import com.zzt.demo.model.enums.SatisfyResultEnum;

import java.io.Serializable;

public class TSatisfyScore implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_satisfy_score.id
     *
     * @mbggenerated Wed Oct 14 16:23:25 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_satisfy_score.user_id
     *
     * @mbggenerated Wed Oct 14 16:23:25 CST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_satisfy_score.in_call
     *
     * @mbggenerated Wed Oct 14 16:23:25 CST 2020
     */
    private String inCall;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_satisfy_score.satisfy_result
     *
     * @mbggenerated Wed Oct 14 16:23:25 CST 2020
     */
    private Integer satisfyResult;


    private SatisfyResultEnum satisfyResultEnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_satisfy_score.create_time
     *
     * @mbggenerated Wed Oct 14 16:23:25 CST 2020
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_satisfy_score.id
     *
     * @return the value of t_satisfy_score.id
     *
     * @mbggenerated Wed Oct 14 16:23:25 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_satisfy_score.id
     *
     * @param id the value for t_satisfy_score.id
     *
     * @mbggenerated Wed Oct 14 16:23:25 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_satisfy_score.user_id
     *
     * @return the value of t_satisfy_score.user_id
     *
     * @mbggenerated Wed Oct 14 16:23:25 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_satisfy_score.user_id
     *
     * @param userId the value for t_satisfy_score.user_id
     *
     * @mbggenerated Wed Oct 14 16:23:25 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_satisfy_score.in_call
     *
     * @return the value of t_satisfy_score.in_call
     *
     * @mbggenerated Wed Oct 14 16:23:25 CST 2020
     */
    public String getInCall() {
        return inCall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_satisfy_score.in_call
     *
     * @param inCall the value for t_satisfy_score.in_call
     *
     * @mbggenerated Wed Oct 14 16:23:25 CST 2020
     */
    public void setInCall(String inCall) {
        this.inCall = inCall == null ? null : inCall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_satisfy_score.satisfy_result
     *
     * @return the value of t_satisfy_score.satisfy_result
     *
     * @mbggenerated Wed Oct 14 16:23:25 CST 2020
     */
    public Integer getSatisfyResult() {
        return satisfyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_satisfy_score.satisfy_result
     *
     * @param satisfyResult the value for t_satisfy_score.satisfy_result
     *
     * @mbggenerated Wed Oct 14 16:23:25 CST 2020
     */
    public void setSatisfyResult(Integer satisfyResult) {
        this.satisfyResult = satisfyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_satisfy_score.create_time
     *
     * @return the value of t_satisfy_score.create_time
     *
     * @mbggenerated Wed Oct 14 16:23:25 CST 2020
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_satisfy_score.create_time
     *
     * @param createTime the value for t_satisfy_score.create_time
     *
     * @mbggenerated Wed Oct 14 16:23:25 CST 2020
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    public SatisfyResultEnum getSatisfyResultEnum() {
        return satisfyResultEnum;
    }

    public void setSatisfyResultEnum(SatisfyResultEnum satisfyResultEnum) {
        this.satisfyResultEnum = satisfyResultEnum;
    }


}