package com.zzt.demo.dao;

import com.zzt.demo.model.TProduct;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    int deleteByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    int insert(TProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    int insertSelective(TProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    TProduct selectByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    int updateByPrimaryKeySelective(TProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(TProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Tue Oct 13 17:03:03 CST 2020
     */
    int updateByPrimaryKey(TProduct record);

    @Select("select product_id as productId  from t_product where product_id = #{productId,jdbcType=VARCHAR}")
    TProduct selectByPrimaryKey1(String productId);

    List<TProduct> getAllBookByPage(@Param("currPage")String currPage, @Param("pageSize")String pageSize);

    int getAllBook();
}